# ==========================
# Application
# ==========================
spring.application.name=config-server

# ==========================
# Server
# ==========================
server.port=8888

# ==========================
# Git Repository
# ==========================
spring.cloud.config.server.git.uri=https://github.com/Sri1223kanth/microservice-config.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true

# ==========================
# Eureka
# ==========================
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true